---
version: "2.1"
services:
  installer:
    image: nicholaswilde/installer
    container_name: installer
    environment:
      - USER=username   #optional
      - GH_TOKEN=token  #optional
      - PORT=3000       #optional
    ports:
      - 3000:3000
    restart: unless-stopped
